#!/usr/bin/env bash

ind_files_dir=$1
temp_file="~temptestoutput"

for f in $(find $ind_files_dir -name '*.ind'); do 
    command-runner.sh test run $f 2>&1 | tee -a $temp_file
done

echo
echo
echo "*******************************************************" 
error=$(grep -B 8 -A 5 ERROR $temp_file)
if [[ -n "$error" ]]; then
    echo "ERROR IN TEST RUN"
    echo "$error"
    if [[ -f "$temp_file" ]]; then
        if [[ ! -d ~/tmp/ ]]; then
            mkdir ~/tmp/
        fi
        mv $temp_file ~/tmp/
    fi
else
    echo "ALL TESTS PASSED"
    if [[ -f "$temp_file" ]]; then
        rm $temp_file
    fi
fi

echo
echo



